### ISSUE TITLE
current version

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-dovecot#1]
Sorry for getting a nuisance - do you have a current version of this repo as well? My own dovecot install is not very docker-ish ;-)

**Comment by tiredofit** [comment]
Hmm, good question. I had planned on building a high powered mail transfer solution a few years ago and our direction shifted. I'll review my private repository code and see if there is anything that differs from this version. I do know however it was working - I just never finished off the entire solution. Will see tomorrow.

**Comment by joergmschulz** [comment]
thank you. Will have a look.

**Comment by tiredofit** [comment]
Sorry, forgot to update you that I polished it up to work with my latest generation images. Personally, I'd find a better image out there. While this works for Mysql and LDAP authentication I think there may be much better images based on dovecot out there. I have not production battle tested this image with thousands of users.

**Comment by joergmschulz** [comment]
maybe https://github.com/joergmschulz/docker-dovecot is of interest for you. it's not thousands of users but a mini-school. concept is to have all users in fusiondirectory, and separated containers for imap, exim as mailout for the internal users, exim as smarthost for this internal host, exim as mailin from extern, mailman3, rspam, clamav (using yours!)
